name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and push Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        cd client
        docker build -t my-react-app-fe .
        docker tag my-react-app-fe ${{ secrets.DOCKER_USERNAME }}/my-react-app-fe
        docker push ${{ secrets.DOCKER_USERNAME }}/my-react-app-fe
        cd ../server
        docker build -t my-react-app-be .
        docker tag my-react-app-be ${{ secrets.DOCKER_USERNAME }}/my-react-app-be
        docker push ${{ secrets.DOCKER_USERNAME }}/my-react-app-be


    - name: SSH into EC2 instance and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          cd bachhv/build3
          docker-compose pull
          docker-compose up -d
          